routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');



/*
 * Routes Sites
 */
Route::get('/contato', 'Site\SiteController@contato');
Route::get('/empresa', 'Site\SiteController@empresa');
Route::get('/post/{id}', 'Site\SiteController@post');
Route::get('/categoria/{id}', 'Site\SiteController@categoria');
Route::get('/', 'Site\SiteController@index');

/****************************************************************************************
 * Rotas do Painel
****************************************************************************************/
Route::group(['prefix' => 'painel', 'middleware' => 'auth'], function (){
    //Usuários
    Route::any('/usuarios/pesquisar', 'Painel\UserController@search')->name('usuarios.search');
    Route::resource('/usuarios', 'Painel\UserController');

   //Categorias
   Route::any('/categorias/pesquisar', 'Painel\CategoriaController@search')->name('categorias.search');
   Route::resource('/categorias', 'Painel\CategoriaController');

    //Posts
    Route::any('/posts/pesquisar', 'Painel\PostController@search')->name('posts.search');
    Route::resource('/posts', 'Painel\PostController');

     //Listagem
     Route::get('/list', function(){
      return view('painel.modulos.list');
     });

      //Forms
      Route::get('/forms', function(){
        return view('painel.modulos.forms');
       });
      
      
    //Raiz painel
    Route::any('/home/pesquisar', 'Painel\PostController@search')->name('home.search');
    Route::resource('/home', 'Painel\HomeController');

});



/**
 * Routes Painel
 */

//  Route::get('/painel/home', function (){

//      return view ('painel.index');
//  });

//  Route::get('/painel/list', function (){

//     return view ('painel.modulos.list');
// });


// Route::get('/painel', function (){

//     return view ('painel.modulos.home');
// });


// // /**
// //  * Routes Painel
// //  */

// Route::get('/painel/home', 'Painel\PainelController@home');
// Route::get('/painel/list', 'Painel\PainelController@list');
// Route::get('/painel/forms', 'Painel\PainelController@forms');

app/Http/Controllers/Painel/CategoriaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Painel\StandardController;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use App\Models\Category;
use DB;

class CategoriaController extends StandardController
{

    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    protected $model;
    protected $modelAuxiliar;
    protected $modelInner;
    protected $modelid = 'categories.id';
    protected $modelname = 'categories.name';
    protected $totalpages = 10;
    protected $views = 'painel.modulos.categorias';
    protected $rotas = 'categorias';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(Category $category)
    {
        $EloqInner =  DB::table('categories');

        $this->modelInner = $EloqInner; 
        $this->model = $category;
        $this->modelAuxiliar = $category;
    }

   
}

resources/views/painel/modulos/categorias/create-edit.blade.php
@extends('painel.templates.dashboard')
@section('conteudo')
<div class="title-pg">
    <h1 class="title-pg">Cadasro de Categoria</h1>
</div>

<div class="content-din">

     <!-- Alert Errors start -->
     @if( isset($errors) && count($errors) > 0 )
     <div class="col-md-12">
         <div class="alert alert-warning alert-dismissible">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
             <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
             @foreach( $errors->all() as $error)
                 <p>{{$error}}</p>
             @endforeach
         </div>
     </div>
    @endif
 <!-- /.Alert Errors start -->
 <!-- form start -->
    @if(isset($data))
    <form 
    class="form form-search form-ds"  
    method="post" action="{{route('categorias.update', $data->id)}}" enctype="multipart/form-data">
        {{ method_field('PUT') }}
    @else
    <form 
    class="form form-search form-ds"  
    method="post" action="{{route('categorias.store')}}" enctype="multipart/form-data">
    @endif
        {{ csrf_field() }} 
    
    <div class="form-group col-md-12">
        <label for="InputName">Nome</label>
        <input type="text" class="form-control" id="InputName" name="name" placeholder="Nome" value="{{$data->name or old('name')}}">
    </div>
    <div class="form-group col-md-12">
        <label for="InputUrl">Url</label>
        <input type="text" class="form-control" id="InputUrl" name="url" placeholder="Url" value="{{$data->url or old('url')}}">
    </div>
    <!-- textarea -->
    <div class="form-group col-md-12">
        <label>Descrição</label>
        <textarea class="form-control" rows="5" name="description" placeholder="Digite aqui ...">{{$data->description or old('description')}}</textarea>
    </div>
    <div class="form-group col-md-12">
        <label for="InputFile">Imagem de Perfil</label>
        <input type="file" id="InputFile" name="image">

    </div>

        <div class="form-group col-md-6">
            <button class="btn btn-info">Enviar</button>
        </div>
    </form>

</div><!--Content Dinâmico-->
@endsection

resources/views/painel/modulos/categorias/index.blade.php
@extends('painel.templates.dashboard')
@section('conteudo')
<div class="title-pg">
    <h1 class="title-pg">Listagem de Categorias</h1>
</div>

<div class="content-din bg-white">

    <div class="form-search">
        <form class="form form-inline"  method="get" action="{{route('categorias.search')}}" enctype="multipart/form-data">

            {{-- {{ csrf_field() }} --}}
            <input type="text" name="pesquisa"  class="form-control">
            {{-- <input type="text" name="email" placeholder="E-mail:" class="form-control"> --}}

            <button type="submit" class="btn btn-search">Pesquisar</button>
        </form>
    </div>

    <div class="class-btn-insert">
    <a href="{{route('categorias.create')}}" class="btn-insert">
            <span class="glyphicon glyphicon-plus"></span>
            Cadastrar
        </a>
    </div>

    <!-- Mensagens enviadas do  controller pela session success -->
      @if( Session::has('success'))
                <div class="col-md-12">
                    <div class="alert alert-success alert-dismissible hide-msgd">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-warning"></i> {{Session::get('success')}}</h4>

                    </div>
                </div>
        @endif
    <!-- /. Mensagens enviadas do  controller pela session success -->

    <table class="table table-striped">
        <tr>
            <th>Nome</th>
            <th>Url</th>
            <th width="150">Ações</th>
        </tr>
        @forelse($datas as $cat)
            <tr>
                <td>{{$cat->name}}</td>
                <td>{{$cat->url}}</td>
                <td>
                <a href="{{route('categorias.show', $cat->id)}}" class="btn btn-info btn-xs"><i class="fa fa-eye"></i></a>
                <a href="{{route('categorias.edit', $cat->id)}}" class="btn btn-success btn-xs"><i class="fa fa-edit"></i></a>

                </td>
            </tr>
            @empty
            <tr>
                <td>Nenhum registro</td>
                </tr>
        @endforelse
    </table>

    {{-- {{$datas->links()}} --}}

    @if(isset($dataForm))
    {{$datas->appends(Request::only('pesquisa'))->links()}}
        @else
    {{$datas->links()}}
        @endif

</div><!--Content Dinâmico-->
@endsection

resources/views/painel/modulos/categorias/show.blade.php
@extends('painel.templates.dashboard')
@section('conteudo')
<div class="title-pg">
<h1 class="title-pg">Visualizar categorias: {{$data->name}}</h1>
</div>

<div class="content-din">
 <!-- Alert Errors start -->
 @if( isset($errors) && count($errors) > 0 )
 <div class="col-md-12">
     <div class="alert alert-warning alert-dismissible">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
         <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
         @foreach( $errors->all() as $error)
             <p>{{$error}}</p>
         @endforeach
     </div>
 </div>

@endif
<!-- /.Alert Errors start -->
 <div class="box-body">
        <div class="row">
            <div class="col-md-8">
         
                <h4><strong>Nome: </strong>{{$data->name}}</h4>
                <h4><strong>Url: </strong>{{$data->url}}</h4>
                <h4><strong>Descrição: </strong>{{$data->description}}</h4>
                
 
            </div>
            <div class="col-md-4">
                @if(isset($data->image))
                <img src="{{URL::asset('/assets/uploads/categorias/'.$data->image)}}" alt="$user->image" class="img-responsive img-rounded img-bordered">
                @endif
            </div>
        </div>
    </div>

    <!-- form start -->
    <form role="form" method="post" action="{{route('categorias.destroy', $data->id)}}" >
        {{ method_field('DELETE') }}
        {{ csrf_field() }}
        <div class="box-footer">
            <div class="form-group col-md-6">
                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Deletar</button>
                <a href="{{route('categorias.index')}}" class="btn btn-info"><i class="fa fa-undo"></i>  Voltar</a>
            </div>
        </div>
    </form>
    

</div><!--Content Dinâmico-->
@endsection